[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.jpeg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.gif"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=31536000"


[build.environment]

[context.production.branch-deploy]
    command = "mv robots-disallow.txt robots.txt"


[context.production]
    command = "mv robots-production.txt robots.txt"